name: SonarCloud
on:
  push:
    branches:
      - main
      - develop
jobs:
    android-unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
          
            # I Need to make gradlew executable
            - name: Make gradlew executable
              working-directory: ./AndroidProject
              run: chmod +x ./gradlew
          
            # Execute unit tests
            - name: Android units tests
              working-directory: ./AndroidProject
              env:
                GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: ./gradlew clean jacocoTestReport sonarqube
              
            # Show a report of the unit tests results
            - name: Android Test Report
              uses: asadmansr/android-test-report-action@v1.2.0
              if: ${{ always() }} # IMPORTANT: run Android Test Report regardless


    android-integration-tests:
        runs-on: macos-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                java-version: 11
          
            # I Need to make gradlew executable
            - name: Make gradlew executable
              working-directory: ./AndroidProject
              run: chmod +x ./gradlew
          
            # Integration Tests
            - name: Android UI tests
              uses: reactivecircus/android-emulator-runner@v2
              with:
                api-level: 29  # api level > 27 seems to be failing at sdk installation step
                working-directory: ./AndroidProject
                profile: pixel_2
                target: google_apis
                disable-animations: true
                emulator-options: -no-window -gpu off -no-snapshot -noaudio -no-boot-anim
                script: ./gradlew connectedCheck
                
            - name: Android UI tests artifacts
              if: always()
              uses: actions/upload-artifact@v2
              with:
                name: ui-tests-artifacts
                path: |
                  ./AndroidProject/app/build/reports/androidTests/connected/
                  ./AndroidProject/app/build/outputs/androidTest-results/connected/