name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      -develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: "marioingelmo"
          project: "MarioIngelmo_TFG-MarioIngelmoDiana"
          token: ${{ secrets.SONAR_TOKEN }}